# Generated by Django 5.0.7 on 2024-08-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['id'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
    ]
